spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springapp
    username: springapp
    password: springapp
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/SpringKeycloakPoc
          jwk-set-uri: http://localhost:8081/realms/SpringKeycloakPoc/protocol/openid-connect/certs


keycloak-rest-client:
  url: http://localhost:8081
