server:
  port: 8080

cors-policies: http://localhost:4200, http://angularapp:4200, http://46.101.176.240:4200/

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/springapp
    username: springapp
    password: springapp
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    open-in-view: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8081/realms/SpringKeycloakPoc
          jwk-set-uri: http://keycloak:8081/realms/SpringKeycloakPoc/protocol/openid-connect/certs

logging:
  level:
    org:
      hibernate: info
      springframework:
        security: info
        web: info

keycloak-rest-client:
  url: http://keycloak:8081
  realm: SpringKeycloakPoc
  client-id: springapp
  admin:
    username: admin
    password: admin
    client-id: admin-cli
