server:
  port: 8080

cors-policies: http://127.0.0.1

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/springapp
    username: springapp
    password: springapp
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8081/realms/SpringKeycloakPoc
          jwk-set-uri: http://keycloak:8081/realms/SpringKeycloakPoc/protocol/openid-connect/certs

logging:
  level:
    org:
      hibernate: info
      springframework:
        security: debug
        web: info

spring-keycloak-poc:
  keycloak:
    url: http://keycloak:8081
    admin:
      username: admin
      password: admin
      client-id: admin-cli
    user:
      client-id: springapp
      realm: SpringKeycloakPoc
