spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/springapp
    username: springapp
    password: springapp
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8081/realms/SpringKeycloakPoc
          jwk-set-uri: http://keycloak:8081/realms/SpringKeycloakPoc/protocol/openid-connect/certs

spring-keycloak-poc:
  keycloak:
    url: http://keycloak:8081
